get http://localhost:3003/api/blogs/

###
post http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtub3QiLCJpZCI6IjY4MjYwODUyY2RjYzdmYzRlNDk2OTNlNyIsImlhdCI6MTc0NzUwNTExMCwiZXhwIjoxNzQ3NTkxNTEwfQ.UHm-qxp9nD-2CnL4CUVGeMmLhtSFCab0gB0zNJOwdLc

{"title":"some new p", "author": "oli", "url":"sdfsdfsdf","likes": 232}

###
post http://localhost:3003/api/users/
Content-Type: application/json

{"username":"kn", "name": "asdflk", "password":"sdjknlkn"}

###
post http://localhost:3003/api/login/
Content-Type: application/json

{"username":"knot", "name": "asdflk", "password":"sdjknlkn"}

###
DELETE http://localhost:3003/api/blogs/682763a5a875e183f72670e2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtub3QiLCJpZCI6IjY4MjYwODUyY2RjYzdmYzRlNDk2OTNlNyIsImlhdCI6MTc0NzQxNTQ4OCwiZXhwIjoxNzQ3NTAxODg4fQ.cAzxRR6oqflVMGXwq8k3f1QPST0fTl1M5ZhXDN4FxrA


###
PUT http://localhost:3003/api/blogs/6813763b333f836365a2e49f
Content-Type: application/json

{"likes": 500}
